import React, { useEffect, useState } from "react"

import DynamicInput from "./base/DynamicInput"

export default function EntityForm(props) {
    const data = props.data || {}

    useEffect(()=>{
        if (props.data) {
            props.onChange(props.data)
        }
    }, [props.data])

    const entityMeta = props.metadata.entities.find((e) => e.name === props.entity)
    const fields = [...props.metadata.baseFields, ...entityMeta.fields]

    const onChange = (name, value) => props.onChange((d) => ({ ...d, [name]: value }))

    return (
        <div>
            {fields.map((f) => (
                <DynamicInput
                    key={f.name}
                    field={f}
                    value={data[f.name]}
                    onChange={(val) => onChange(f.name, val)}
                    disabled={ f.autoGenerated && !props.id }
                />
            ))}
        </div>
    )
}
